### ISSUE TITLE
括号了的functional programs 翻译成[应用类程序]更恰当些

### ISSUE THREAD

**Issue by yubaoquan** [justinyhuang/Functional-Programming-For-The-Rest-of-Us-Cn#20]
rt

**Comment by SnowOnion** [comment]
@yubaoquan 你指的是 [FunctionalProgrammingForTheRestOfUs.en.md](FunctionalProgrammingForTheRestOfUs.en.md) 里的
(this is particularly true about functional programs)
还是
 (yes, you could write functional programs in Java if you felt particularly masochistic)
呢？

**Comment by yubaoquan** [comment]
前一个
