### ISSUE TITLE
翻译错误

### ISSUE THREAD

**Issue by codeworm96** [justinyhuang/Functional-Programming-For-The-Rest-of-Us-Cn#24]
“We want sendToSEC executed unless the stock is European.” 被翻译为“程序中只有在stock为European的时候才执行sendToSEC。”
实际应该是执行 sendToSEC 除非 stock 为 European。即在stock为European的时候不执行sendToSEC，其他情况都执行。
这点可以在下面的代码和“请注意，如果condition值为真，那就不会计算code。”中得到印证。

**Comment by justinyhuang** [comment]
Thank you and could you submit a PR?

**Comment by codeworm96** [comment]
Sure.
