### ISSUE TITLE
我的Presentation Slides

### ISSUE THREAD

**Issue by ProfessorX** [justinyhuang/Functional-Programming-For-The-Rest-of-Us-Cn#7]
https://github.com/ProfessorX/CIS502/tree/master/Presentation

下面FunctionalPro那个。

去年给软件工程课做的。喜欢就加进来吧，我感觉整篇文章基本覆盖到了。

**Update**
好吧，其实没有覆盖到整篇文章。后面的Curry和Lazy有很多没有讲到——没办法，毕竟那时候每个人只有30分钟的时间。

**Comment by justinyhuang** [comment]
not an issue for this translation project.
